language: cpp
sudo: false
compiler: clang
addons:
  apt:
    packages:
      - libgmp-dev
      - libntl-dev
script:
  - cd src/
  - make -j
  - make test
  - make clean
notifications:
  email: false
