language: cpp
sudo: true
compiler: clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y libgmp-dev libntl-dev
script:
  - cd src/
  - make -j
  - make test
  - make clean
notifications:
  email: false
