langage: cpp
sudo: required
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
before_install:
  - if [ $TRAVIS_OS_NAME == linux]; then sudo apt-get -qq update; apt-get install -y libgmp-dev libntl-dev; fi
  - if [ $TRAVIS_OS_NAME == osx]; then brew update; brew install gmp ntl; fi
install: true
script:
  - cd src/
  - make -j
  - make test
  - make clean
