link = cxx = "g++-4.7"
env = Environment(CXX=cxx,
                  CXXFLAGS="-Wall -Wextra -Weffc++ -pedantic -O3 -m64 -std=c++11",
                  LINK=link,
                  LINKFLAGS="-Wall -lntl -lgmp")

# If you wish to get rid of just the object files, run `scons -c tidy`
env.Clean("tidy", Glob("*.o"))

[env.Program(name + ".out", name + ".cc") for name in
    Split("curves_test points_test key_demo ecoh_echo")]
